apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-server-deployment
  labels:
    app: mail-server
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: mail-server
  template:
    metadata:
      labels:
        app: mail-server
    spec:
      containers:
        - name: mail-server
          image: mail-server:1
          envFrom:
            - secretRef:
                name: mail-server-secret
            - secretRef:
                name: rabbit-mq-secret
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mail-server-service
  labels:
    app: mail-server
spec:
  selector:
    app: mail-server
  ports:
    - port: 3003
      targetPort: 8080
  type: ClusterIP
