spring:
  mail:
    host: ${SPRING_MAIL_HOST}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    port: ${SPRING_MAIL_PORT}
    protocol: ${SPRING_MAIL_PROTOCOL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  thymeleaf:
    cache: false

rabbit:
  activate-account:
    queue-name: ${RABBIT_MAIL_SERVER_ACTIVATE_ACCOUNT_QUEUE_NAME}
    routing-key: ${RABBIT_MAIL_SERVER_ACTIVATE_ACCOUNT_ROUTING_KEY}

  send-vacancy-response:
    queue-name: ${RABBIT_MAIL_SERVER_SEND_VACANCY_RESPONSE_QUEUE_NAME}
    routing-key: ${RABBIT_MAIL_SERVER _SEND_VACANCY_RESPONSE_ROUTING_KEY}

  send-payment-order:
    queue-name: ${RABBIT_MAIL_SERVER_SEND_PAYMENT_ORDER_QUEUE_NAME}
    routing-key: ${RABBIT_MAIL_SERVER_SEND_PAYMENT_ORDER_ROUTING_KEY}

  send-info-about-success-payment:
    queue-name: ${RABBIT_MAIL_SERVER_SEND_INFO_ABOUT_SUCCESS_PAYMENT_QUEUE_NAME}
    routing-key: ${RABBIT_MAIL_SERVER_SEND_INFO_ABOUT_SUCCESS_PAYMENT_ROUTING_KEY}

service:
  host: ${SERVICE_HOST}

mail:
  debug: ${MAIL_DEBUG}

endpoint:
  activation: activation